# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test
pod 'Firebase/Firestore'
pod 'YouTubePlayer'
pod 'FirebaseFirestoreSwift'
pod "YoutubePlayer-in-WKWebView", "~> 0.3.0"

end
